---

- hosts:
    - controlplane

  tasks:

    - name: Run a command that uses non-posix shell-isms (in this example /bin/sh doesn't handle redirection and wildcards together but bash does)
      ansible.builtin.shell: ip -4 addr show | grep "inet" | egrep -v '(dynamic|127\.0\.0)' | awk '{print $2}' | cut -d/ -f1
      args:
        executable: /bin/bash
      register: primary_ip

    # - ansible.builtin.shell:
    #     cmd: ip -4 addr show | grep "inet" | egrep -v '(dynamic|127\.0\.0)' | awk '{print $2}' | cut -d/ -f1
    #   args:
    #     executable: /bin/bash
    #   register: primary_ip

    - debug:
        msg: "{{ primary_ip.stdout }}"
...