---

- name: Copy the keys into memory
  become: true
  delegate_to: localhost
  slurp:
    src: "/etc/ssl/kthw/private/{{item}}.key"    
  loop: "{{ cert_names }}"
  register: slurped_key

- name: Copy the key files to the hosts
  copy:
    dest: /home/vagrant/{{item.item}}.key
    owner: vagrant
    mode: 0600
    content: "{{ item.content | b64decode }}"
  loop: "{{ slurped_key.results }}"

- name: Copy the certs to the hosts
  copy:
    src: "/etc/ssl/kthw/crt/{{item}}.crt"
    dest: "/home/vagrant/{{item}}.crt"
  loop: "{{ cert_names }}"

- name: Copy the kubeconfigs to the hosts
  copy:
    src: "/kubeconfigs/{{item}}.kubeconfig"
    dest: "/home/vagrant/{{item}}.kubeconfig"
  loop: "{{ kubeconfig_names }}"

...